# Generated by Django 5.0.1 on 2024-01-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="", max_length=20),
        ),
    ]
