# Generated by Django 5.0.1 on 2024-01-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_e6a359_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
