# Generated by Django 5.0.1 on 2024-01-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20240125_0349"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="store_custo_last_na_2e448d_idx",
            old_name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customer",
        ),
    ]
