# Generated by Django 5.0.1 on 2024-01-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0007_rename_store_custo_last_na_e6a359_idx_store_custo_last_na_2e448d_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="place_at",
            new_name="placed_at",
        ),
    ]
