# Generated by Django 5.0.1 on 2024-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_place_at_order_placed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(null=True, to="store.promotion"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
    ]
