# Generated by Django 5.0.2 on 2024-02-09 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_collection_featured_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f0336acd-4b72-475f-b0b6-7e3c9b3ceb65"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
