# Generated by Django 5.0.2 on 2024-02-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
