# Generated by Django 5.0.2 on 2024-02-12 23:07

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
    ]
