# Generated by Django 5.0.2 on 2024-02-17 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [
                    ("view_history", "Can view history"),
                    ("upload_productimage", "Can upload product image"),
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="total_sells",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
