# Generated by Django 5.0.2 on 2024-02-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_customer_options_alter_productimage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "permissions": [("upload_productimage", "Can upload product image")]
            },
        ),
    ]
