# Generated by Django 5.0.2 on 2024-02-18 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_orderitem_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                choices=[
                    (Decimal("1"), "1"),
                    (Decimal("1.5"), "1.5"),
                    (Decimal("2"), "2"),
                    (Decimal("2.5"), "2.5"),
                    (Decimal("3"), "3"),
                    (Decimal("3.5"), "3.5"),
                    (Decimal("4"), "4"),
                    (Decimal("4.5"), "4.5"),
                    (Decimal("5"), "5"),
                ],
                decimal_places=1,
                default=1,
                max_digits=2,
            ),
            preserve_default=False,
        ),
    ]
