export const  LIKES_ADD_ITEM='LIKES_ADD_ITEM'
export const  LIKES_REMOVE_ITEM='LIKES_REMOVE_ITEM'

export const LIKES_DETAILS_REQUEST = 'LIKES_DETAILS_REQUEST';
export const LIKES_DETAILS_SUCCESS = 'LIKES_DETAILS_SUCCESS';
export const LIKES_DETAILS_FAIL = 'LIKES_DETAILS_FAIL';